### ISSUE TITLE
Blender 3.2.0 doesn't update categories and materials

### ISSUE THREAD

**Issue by B-Rodion** [TrueCryer/blendermada_client#29]
Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balbasyants\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blendermada.py", line 709, in execute
    update_categories(context)
  File "C:\Users\balbasyants\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blendermada.py", line 515, in update_categories
    for i in get_categories():
  File "C:\Users\balbasyants\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blendermada.py", line 365, in get_categories
    r = bmd_urlopen('/api/materials/categories.json')
  File "C:\Users\balbasyants\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blendermada.py", line 333, in bmd_urlopen
    return request.urlopen('%s?%s' % (full_url, params))
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

**Comment by michaelwazowskyitaly** [comment]
me too
